services:
  # api:
  #   build: ../apps/api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - REDIS_URL=${REDIS_URL}
  #     - PORT=3000
  #   depends_on:
  #     - db
  #     - redis
  # dashboard:
  #   build: ./apps/dashboard
  #   ports:
  #     - 5173:5173
  # worker:
  #   build: ./apps/worker
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_queue
    ports:
      - 5432:5432
    volumes:
      - event_queue_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4318:4318
volumes:
  event_queue_data:
  redis_data:
  grafana_data: